services:
  lambkin_dev:
    build:
      context: ../../..
      dockerfile: examples/beluga/docker/Dockerfile
    image: lambkin_ros:jazzy
    container_name: lambkin_developer
    network_mode: "host"
    stdin_open: true
    tty: true
