#! /usr/bin/env python3

import argparse
import os
import pathlib
import rospy

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description='Generate a map from a ROS 1 bag file.')
    parser.add_argument(
        '-b', '--bag-path', type=pathlib.Path,
        requred=True, help=(
            'Full path to the .bag file to be used for mapping.'))
    parser.add_argument(
        '-o', '--output-dir', default=None, help=(
            'Full path where the maps file are going to be dumped to.'
            'Defaults to bag directory.'))
    

def main():
    args = parse_args()
    assert args.bag_path.is_file(), f"Bag file {args.bag_path.resolve()} doesn't exist"
    if args.output_dir is None:
        args.output_dir = args.bag_path.parent_path()
    else:
        os.makedirs(os.path.dirname(args.output_dir), exist_ok=True)
    
    rospy.Subscriber


if __name__ == '__main__':
    main()
