# Copyright 2024 Ekumen, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

VERSION 0.8

IMPORT ../../external/os AS os
IMPORT ../../external/packaging/poetry AS poetry

build:
    FROM poetry+environment
    COPY . .
    RUN poetry build -o sdist
    SAVE ARTIFACT ./sdist

embed-ubuntu-devel:
    ARG distro
    FROM os+ubuntu --distro=$distro
    COPY requirements.txt pyproject.toml poetry.lock .
    RUN pip install -r requirements.txt
    RUN poetry config virtualenvs.create false
    RUN poetry install --no-root --with dev

embed-ubuntu-release:
    ARG distro
    FROM os+ubuntu --distro=$distro
    COPY +build/sdist/*.whl /tmp/.
    RUN pip install $(ls /tmp/lambkin_shepherd*.whl)[full]
