---
- name: Setup beluga vs nav2
  hosts: localhost
  connection: local
  vars:
    ansible_bender:
      base_image: "docker.io/osrf/ros:noetic-desktop-full-focal"

      working_container:
        volumes:
          - "/home/erasmo/Projects/Ekumen/lambkin/src/benchmarks/beluga_vs_nav2:/workspace/src/package/beluga_vs_nav2"

      target_image:
        name: ekumenlabs/beluga-vs-nav2:latest

  tasks:
    - name: Install core dependencies
      ansible.builtin.include_tasks: inventory/core/tasks/main.yml

    - name: Install runner components
      ansible.builtin.include_tasks: inventory/runner/tasks/main.yml

    - name: Add the Kisak Mesa PPA
      ansible.builtin.apt_repository:
        repo: ppa:kisak/kisak-mesa
        state: present

    - name: Install packages
      ansible.builtin.apt:
        name:
          - software-properties-common
          - libegl-mesa0
          - libglx-mesa0
        state: present

    - name: Clone Beluga repository
      ansible.builtin.git:
        repo: https://github.com/Ekumen-OS/beluga
        dest: /workspace/src/beluga
        version: main

    - name: Clone navigation2 repository
      ansible.builtin.git:
        repo: https://github.com/ros-planning/navigation2.git
        dest: /workspace/src/navigation2
        depth: 1

    - name: Set up sparse-checkout for nav2_amcl in navigation2 repository
      ansible.builtin.command: git sparse-checkout set nav2_amcl && git checkout
      args:
        chdir: /workspace/src/navigation2

    - name: Update and upgrade apt packages
      ansible.builtin.apt:
        update_cache: yes
        upgrade: yes

    - name: Update ROS dependencies
      ansible.builtin.command: rosdep update
      args:
        chdir: /workspace

    - name: Install ROS dependencies and build
      ansible.builtin.command: rosdep install -i -y --from-paths src --skip-keys 'lambkin-shepherd flatland_server beluga_example beluga_benchmarks flatland_plugins'
      args:
        chdir: /workspace

    - name: Colcon build
      ansible.builtin.command: colcon build --packages-up-to 'beluga_vs_nav2' --merge-install --install-base /opt/ros/application
      args:
        chdir: /workspace
    
    - name: Insert content into entrypoint.bash
      blockinfile:
        path: /opt/ros/application/entrypoint.bash
        block: |
          # Auto-generated with Docker Buildkit
          source /opt/ros/application/setup.bash
          if [ $# -ne 0 ]; then
              ros2 run beluga_vs_nav2 $@
          else
              bash
          fi
