- name: Setup beluga vs nav2
  hosts: localhost
  connection: local
  vars:
    ansible_bender:
      base_image: "docker.io/osrf/ros:noetic-desktop-full-focal"

      working_container:
        volumes:
          - "/home/erasmo/Projects/Ekumen/lambkin/src/benchmarks/cartographer_ros_benchmarks:/tmp/cartographer_ros_benchmarks"
          - "/home/erasmo/Projects/Ekumen/lambkin/src/benchmarks/cartographer_ros_benchmarks:/tmp/ws/src/package/cartographer_ros_benchmarks"

      target_image:
        name: ekumenlabs/beluga-vs-nav2:latest

  tasks:
    - name: Install core dependencies
      ansible.builtin.include_tasks: inventory/core/tasks/main.yml
    
    - name: Install runner components
      ansible.builtin.include_tasks: inventory/runner/tasks/main.yml

    - name: Create /tmp/ws directory
      file:
        path: /tmp/ws
        state: directory
        mode: '0755'

    - name: Download cartographer_ros.rosinstall
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/cartographer-project/cartographer_ros/master/cartographer_ros.rosinstall
        dest: /tmp/ws/
        mode: '0644'

    - name: Init cartographer
      ansible.builtin.command: wstool init src cartographer_ros.rosinstall
      args:
        chdir: /tmp/ws/

    - name: Update APT cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install required packages
      ansible.builtin.apt:
        name:
          - libgmock-dev
          - ninja-build
          - stow
        state: present

    - name: Set up Abseil
      ansible.builtin.command: |
        sudo src/cartographer/scripts/install_abseil.sh && \
        rosdep update && \
        rosdep install -y -i --from-paths src --skip-keys libabsl-dev
      args:
        chdir: /tmp/ws/
    
    - name: chmod
      ansible.builtin.command: chmod +x ./opt/ros/{{ ansible_env.ROS_DISTRO }}/setup.bash

    - name: Run catkin_make_isolated
      ansible.builtin.command: |
        ./opt/ros/{{ ansible_env.ROS_DISTRO }}/setup.bash && \
        catkin_make_isolated --install-space /opt/ros/{{ ansible_env.ROS_DISTRO }}-extras --install --merge

    - name: Append ROS setup to /etc/profile.d/ros.sh
      lineinfile:
        path: /etc/profile.d/ros.sh
        line: '. /opt/ros/{{ ansible_env.ROS_DISTRO }}-extras/setup.sh'

    - name: Update APT cache
      ansible.builtin.apt:
        update_cache: true 

    - name: Update ROS dependencies database
      ansible.builtin.command: rosdep update
      args:
        chdir: /tmp/ws/src


    - name: Install ROS dependencies
      ansible.builtin.command: rosdep install -i -y --from-path /tmp/ws/src --skip-keys 'lambkin-shepherd'
      args:
        chdir: /tmp/ws/src

    - name: Clean up APT cache
      ansible.builtin.apt:
        autoclean: true

    - name: Name
      ansible.builtin.command:
        catkin_make_isolated --install --merge --install-space /opt/ros/application
      args:
        chdir: /tmp/ws

    - name: Create entrypoint.bash
      ansible.builtin.copy:
        content: |
          # Auto-generated with Ansible
          source /opt/ros/application/setup.bash
          if [ $# -ne 0 ]; then
              rosrun cartographer_ros_benchmarks $@
          else
              bash
          fi
        dest: /opt/ros/application/entrypoint.bash
        mode: '0755'
