---
- name: Setup a slam toolbox benchmarks
  hosts: localhost
  connection: local
  vars:
    ansible_bender:
      base_image: "docker.io/osrf/ros:noetic-desktop-full-focal"

      working_container:
        volumes:
          - "/home/erasmo/Projects/lambkin/src/benchmarks/slam_toolbox_benchmarks:/tmp/ws/src/package"

      target_image:
        name: ekumenlabs/slam-toolbox-benchmarks:latest

  tasks:
    - name: Install core dependencies
      ansible.builtin.include_tasks: inventory/core/tasks/main.yml

    - name: Install runner components
      ansible.builtin.include_tasks: inventory/runner/tasks/main.yml

    - name: Install ros-noetic-pointcloud-to-laserscan
      ansible.builtin.apt:
        name: ros-noetic-pointcloud-to-laserscan
        state: present

    - name: Run rosdep install
      ansible.builtin.command: "rosdep install -i -y --from-path src --skip-keys 'lambkin-shepherd'"
      args:
        chdir: /tmp/ws
