services:
  lambkin_dev:
    build: .
    image: lambkin_ros:jazzy
    container_name: lambkin_developer
    network_mode: "host"

    stdin_open: true
    tty: true

    volumes:
      - ..:/ws
      - ${HOME}/ekumen/rosbags/reference_files:/rosbags/reference
      - ${HOME}/ekumen/rosbags/benchmarking_results:/benchmarking_results
