- name: Check package manager (apt-get or other)
  shell: |
    if command -v apt-get > /dev/null; then
      echo "apt-get"
    else
      echo "unknown"
    fi
  register: package_manager

- name: Install basic dependencies
  ansible.builtin.apt:
    name:
    - adduser
    - bash
    - coreutils
    - curl
    - git
    - python3
    - python3-pip
    - sed
    - tar
    state: present
  when: package_manager.stdout == "apt-get"
  tags:
  - basic_dependencies

- name: Configure keyboard and locales
  apt:
    name: "{{ item }}"
    state: present
  when: package_manager.stdout == "apt-get"
  loop:
  - keyboard-configuration
  - locales
  tags:
  - keyboard_and_locales

- name: Generate en_US.UTF-8 locale
  command: locale-gen en_US.UTF-8
  when: package_manager.stdout == "apt-get"
  tags:
  - generate_locale

- name: Install Python 3.x build dependencies
  ansible.builtin.apt:
    name:
    - build-essential
    - git
    - libbz2-dev
    - libffi-dev
    - libgdbm-compat-dev
    - libgdbm-dev
    - liblzma-dev
    - libncurses5-dev
    - libreadline6-dev
    - libsqlite3-dev
    - libssl-dev
    - lzma
    - lzma-dev
    - pkg-config
    - tk-dev
    - uuid-dev
    - zlib1g-dev
    state: present
  when: package_manager.stdout == "apt-get"
  tags:
  - python_build_dependencies


- name: Fail if unknown package manager
  fail:
    msg: "Unknown package manager"
  when: package_manager.stdout == "unknown"
  tags:
  - unknown_package_manager
