services:
  devcontainer:
    image: ekumenlabs/cartographer-ros-benchmarks:dev
    container_name: cartographer-ros-benchmarks-dev
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/tmp/.docker.xauth
    stdin_open: true
    tty: true
    privileged: ${PRIVILEGED:-false}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth
      - ../../..:/workspace/src/lambkin
    working_dir: /workspace
