name: pytest

on:
  push:
    branches: [ next-gen ]
  pull_request:
    branches: [ next-gen ]

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.12"
          enable-cache: true

      - name: Install project dependencies
        run: uv sync --group dev

      - name: Run pytest
        run: uv run pytest
